src/Api/Areas/Notebooks/Pages/Delete.cshtml.cs
using CloudDrive.Services.Notebooks;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CloudDrive.Api.Areas.Notebooks.Pages
{
    public class DeletePage : PageModel
    {
        private readonly INotebooksService _service;

        [BindProperty]
        public NotebookDto Notebook { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        public DeletePage(INotebooksService service)
        {
            _service = service;
        }

        public async Task OnGet()
        {
            ViewData["Page Title"] = " On Delete";

            if (Id > 0)
            {
                var result = await _service.Get(Id);

                if (result.IsSuccssfull)
                {
                    Notebook = result.Data;
                }
            }
        }

        public async Task<IActionResult> OnPost()
        {
            ViewData["Page Title"] = " On Delete";

            if (Notebook.Id > 0)
            {
                await _service.Delete(Notebook.Id);
            }

            return LocalRedirect("/notebooks");
        }
    }
}

src/Api/Areas/UserCreditCards/Pages/Delete.cshtml.cs
using CloudDrive.Services.CreditCards;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.CreditCards;

namespace clouddrive.Areas.UserCreditCards.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly ICreditCardsServices _service;
        [BindProperty]
        public CloudDrive.Domain.Result<CreditCardsDto> credirCard { get; set; }
        [BindProperty]
        public int CardId { get; set; }

        public DeleteModel(ICreditCardsServices service)
        {
            _service = service;
        }

        public async Task OnGet(int Id)
        {
            var result = await _service.GetAsync(Id);
            CardId = Id;
            credirCard = result;

        }
        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            else
            {
                var result = await _service.DeleteAsync(credirCard.Data.Id);
                credirCard.IsSuccssfull = result.IsSuccssfull;
                credirCard.Message = result.Message;
                return LocalRedirect("/Index");
            }
        }
    }
}

src/Api/Areas/UserCreditCards/Pages/Edit.cshtml.cs
using CloudDrive.Domain;
using CloudDrive.Domain.Entities;
using CloudDrive.Services.CreditCards;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.CreditCards;

namespace clouddrive.Areas.UserCreditCards.Pages
{
	public class EditModel : PageModel
	{
		private readonly ICreditCardsServices _service;
		[BindProperty]
		public CreditCardsDto cardsDto { get; set; }
		[BindProperty]
		public int Id { get; set; }
		public Result<CreditCardsDto> creditCards { get; set; }
		public EditModel(ICreditCardsServices service)
		{
			_service = service;
		}

		public async Task OnGetUpdateAsync(int Id)
		{
			cardsDto = new CreditCardsDto();
			if (Id == 0)
			{
				cardsDto = null;
			}
			else
			{
				var result = await _service.GetAsync(Id);
				if (result.IsSuccssfull)
				{
					ViewData["PageTitle"] = "Update";
				}
				else
				{
					ViewData["PageTitle"] = "Insert";
				}
				cardsDto = result.Data;

			}




		}
		public async Task<IActionResult> OnPost()
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}
			else
			{
				if (Id > 0)
				{
					creditCards = await _service.UpdateAsync(Id, cardsDto);
				}
				else
				{
					UserCreditCard card = new UserCreditCard();
					card.UserId = cardsDto.UserId;
					card.CreditCardNumber = cardsDto.CreditCardNumber;
					card.CreditCardSecretCode = cardsDto.CardSecretCode;
					card.HolderName = cardsDto.HolderName;
					card.ExpireYear = cardsDto.ExpireYear;
					card.ExpireMonth = cardsDto.ExpireMonth;
					creditCards = await _service.InsertAsync(card);

				}
				return Page();
			}

		}
	}
}

src/Api/Areas/UserCreditCards/Pages/Index.cshtml.cs
using CloudDrive.Domain;
using CloudDrive.Services.CreditCards;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.CreditCards;

namespace clouddrive.Areas.UserCreditCards.Pages
{
	public class IndexModel : PageModel
	{
		private readonly ICreditCardsServices _service;

		public Result<List<CreditCardsDto>> Cards { get; set; }

		[BindProperty]
		public int Id { get; set; }
		public IndexModel(ICreditCardsServices service)
		{
			_service = service;
			Cards = new Result<List<CreditCardsDto>>();
		}

		public async void OnGet(string Id)
		{
			if (!string.IsNullOrEmpty(Id))
			{
				var result = await _service.GetAllAsync(Id);
				if (result.IsSuccssfull)
				{
					Cards = result;
				}
				else
				{
					Cards.Message = result.Message;
					Cards.IsSuccssfull = result.IsSuccssfull;
				}
			}

		}
	}
}

src/Api/Areas/UserCreditCards/Pages/UserList.cshtml.cs
using CloudDrive.Domain;
using CloudDrive.Services.CreditCards;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.CreditCards;

namespace clouddrive.Areas.UserCreditCards.Pages
{
    public class UserListModel : PageModel
    {
        private readonly ICreditCardsServices _service;

        public UserListModel(ICreditCardsServices service)
        {
            _service = service;
        }
        [BindProperty]
        public Result<List<CreditCardsDto>> users { get; set; }
        


        public async Task OnGet()
        {
            users = await _service.ListAllUsersAsync();

        }
    }
}

src/Api/Areas/UserPasswords/Pages/Delete.cshtml.cs
using CloudDrive.Services.UserPasswords;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CloudDrive.Api.Areas.UserPasswords.Pages
{
	public class DeletePage : PageModel
	{
		private readonly IUserPasswordsService _service;

		[BindProperty]
		public UserPasswordDto UserPassword { get; set; }

		[BindProperty(SupportsGet = true)]
		public int Id { get; set; }

		public DeletePage(
			IUserPasswordsService service
		)
		{
			_service = service;
		}

		public async Task OnGet()
		{
			ViewData["PageTitle"] = "On Delete";

			if (Id > 0)
			{
				var result = await _service.GetAsync(Id);

				if (result.IsSuccssfull)
				{
					UserPassword = result.Data;
				}
			}
		}

		public async Task<IActionResult> OnPost()
		{
			await _service.DeleteAsync(UserPassword.Id);

			return LocalRedirect("/user-passwords");
		}
	}
}

src/Api/Controllers/Api/UserCreditCardsController.cs
using CloudDrive.Domain.Entities;
using CloudDrive.Services.CreditCards;
using Microsoft.AspNetCore.Mvc;
using Services.CreditCards;

namespace clouddrive.Controllers.Api
{
	[Route("/api/UserCreditCards")]
	public class ApiUserCreditCardsController : Controller
	{
		private readonly ICreditCardsServices _creditCardsService;
		public ApiUserCreditCardsController(ICreditCardsServices creditCardsService)
		{
			_creditCardsService = creditCardsService;
		}

		[HttpGet("{id}")]
		/*
         * Get CreditCard for the user 
         */
		public async Task<IActionResult> GetCreditCard(int id)
		{
			var userCreditCard = await _creditCardsService.GetAsync(id);


			if (userCreditCard == null)
			{
				return NotFound(userCreditCard);
			}
			else
			{
				return Ok(userCreditCard);
			}

		}
		[HttpGet("user/{userId}")]
		public async Task<IActionResult> GetUserCreditCards(string userId)
		{
			var userCreditCards = await _creditCardsService.GetAllAsync(userId);

			if (userCreditCards.IsSuccssfull)
			{
				return Ok(userCreditCards);
			}
			else
			{
				return NotFound(userCreditCards);
			}
		}

		[HttpPost]
		public async Task<IActionResult> CreateUserCreditCard([FromBody] UserCreditCard userCreditCard)
		{
			var result = await _creditCardsService.InsertAsync(userCreditCard);

			if (result.IsSuccssfull)
			{
				return Ok(result);

			}
			else
			{
				return BadRequest(result);
			}
		}

		[HttpPut("{id}")]
		public async Task<IActionResult> UpdateUserCreditCard(int id, [FromBody] CreditCardsDto userCreditCard)
		{
			var result = await _creditCardsService.UpdateAsync(id, userCreditCard);
			if (result.IsSuccssfull)
			{
				return Ok(result);
			}
			else
			{
				return NotFound(result); ;
			}

		}

		[HttpDelete("{id}")]
		public async Task<IActionResult> DeleteUserCreditCard(int id)
		{
			var result = await _creditCardsService.DeleteAsync(id);
			if (result.IsSuccssfull)
			{

				return Ok(result);
			}
			else
			{
				return NotFound(result);
			}
		}


	}
}

src/Api/Controllers/UserCreditCardsController.cs
/*using CloudDrive.Domain;
using CloudDrive.Domain.Entities;
using CloudDrive.Services.CreditCards;
using Microsoft.AspNetCore.Mvc;
using Services.CreditCards;

namespace clouddrive.Controllers
{
    [Route("UserCreditCards")]
    public class UserCreditCardsController : Controller
    {
        private readonly ICreditCardsServices _creditCardsServices;

        public UserCreditCardsController(ICreditCardsServices creditCardsServices)
        {
            _creditCardsServices = creditCardsServices;
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Index(int id)
        {
            Result<List<CreditCardsDto>> result = await _creditCardsServices.GetAllAsync(id);

            return View(result);
        }
        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }
    }
}
*/

src/Api/Areas/UserCreditCards/Pages/Delete.cshtml
@page "/userCredit/Delete/{Id}"
@model clouddrive.Areas.UserCreditCards.Pages.DeleteModel
@{
        Layout = "/Views/Shared/_Layout.cshtml";

}

<form asp-area="UserCreditCards" asp-page="Delete" asp-route-id="Id" method="post">
    <input asp-for="credirCard.Data.Id" hidden />
    <div>
        <div>
            <label asp-for="credirCard.Data.CreditCardNumber"></label>
            <input asp-for="credirCard.Data.CreditCardNumber" disabled/>
        </div>
        <div>
            <label asp-for="credirCard.Data.ExpireMonth"></label>
            <input asp-for="credirCard.Data.ExpireMonth" disabled/>
        </div>
        <div>
            <label asp-for="credirCard.Data.ExpireYear"></label>
            <input asp-for="credirCard.Data.ExpireYear" disabled/>
        </div>
        <div>
            <label asp-for="credirCard.Data.HolderName"></label>
            <input asp-for="credirCard.Data.HolderName" disabled/>
        </div>
        <div>
            <label asp-for="credirCard.Data.CardSecretCode"></label>
            <input asp-for="credirCard.Data.CardSecretCode" disabled />
        </div>
    </div>
    <button type="submit" class="btn btn-success">Delete</button>
</form>

src/Api/Areas/UserCreditCards/Pages/Edit.cshtml
@page "/userCredit/{handler}/{id?}"
@model clouddrive.Areas.UserCreditCards.Pages.EditModel
@{
	Layout = "/Views/Shared/_Layout.cshtml";
}
<form asp-area="UserCreditCards" asp-page="/Edit" asp-route-id="Id" method="post">
	@{
		if (Model.cardsDto != null)
		{
			<input asp-for="cardsDto.UserId" />
		}
	}
	<div>
		<div>
			<label asp-for="cardsDto.UserId"></label>
			<input asp-for="cardsDto.UserId" />
		</div>
		<div>
			<label asp-for="cardsDto.CreditCardNumber"></label>
			<input asp-for="cardsDto.CreditCardNumber" />
		</div>
		<div>
			<label asp-for="cardsDto.ExpireMonth"></label>
			<input asp-for="cardsDto.ExpireMonth" />
		</div>
		<div>
			<label asp-for="cardsDto.ExpireYear"></label>
			<input asp-for="cardsDto.ExpireYear" />
		</div>
		<div>
			<label asp-for="cardsDto.HolderName"></label>
			<input asp-for="cardsDto.HolderName" />
		</div>
		<div>
			<label asp-for="cardsDto.CardSecretCode"></label>
			<input asp-for="cardsDto.CardSecretCode" />
		</div>
	</div>
	<button type="submit" class="btn btn-success">Submit</button>
</form>

src/Api/Areas/UserCreditCards/Pages/Index.cshtml
@page "/userCredit/user/{id}"
@model clouddrive.Areas.UserCreditCards.Pages.IndexModel
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["PageTitle"] = "Index";
}

<h2>List all Credit Cards for user</h2>
    <a asp-area="UserCreditCards" asp-page="Edit" asp-page-handler="Update" >Add new </a>

<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
          <thead  class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th class="px-6 py-3">ID</th>
              <th class="px-6 py-3">Holder Name</th>
              <th class="px-6 py-3">Card Number</th>
              <th class="px-6 py-3">Expire Date</th>
              <th class="px-6 py-3">Action</th>
            </tr>
          </thead>
          <tbody>
                @if(Model.Cards.IsSuccssfull){
                    @foreach(var card in Model.Cards.Data)
                    {
                        <user-credit itemid="@card.Id" card='@Json.Serialize(card)'></user-credit>
                
                    }
         
                
                }
                else
                {
                    <tr>
                        <td colspan="5">@Model.Cards.Message</td>
                    </tr>
         
                }

 
          </tbody>
    </table>
</div>

@section Scripts{
    <script src="/components/UserCreditCards.js"></script>

}

src/Api/Areas/UserCreditCards/Pages/UserList.cshtml
@page "/userCredit"
@model clouddrive.Areas.UserCreditCards.Pages.UserListModel
@{
}

<h2>List of All users </h2>
<table>
	<thead>
		<tr>
			<th>UserId</th>
			<th>Name</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>

		@foreach (var user in Model.users.Data)
		{
			<tr>
				<td>@user.UserId</td>
				<td>@user.HolderName</td>
				<td>
					<a asp-area="UserCreditCards" asp-page="Index" asp-page-handler="user"
						asp-route-id="@user.UserId">View</a>
				</td>
			</tr>
		}
	</tbody>
</table>