src/Api/Areas/Notebooks/Pages/Delete.cshtml.cs
using CloudDrive.Services.Notebooks;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CloudDrive.Api.Areas.Notebooks.Pages
{
    public class DeletePage : PageModel
    {
        private readonly INotebooksService _service;

        [BindProperty]
        public NotebookDto Notebook { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        public DeletePage(INotebooksService service)
        {
            _service = service;
        }

        public async Task OnGet()
        {
            ViewData["Page Title"] = " On Delete";

            if (Id > 0)
            {
                var result = await _service.Get(Id);

                if (result.IsSuccssfull)
                {
                    Notebook = result.Data;
                }
            }
        }

        public async Task<IActionResult> OnPost()
        {
            ViewData["Page Title"] = " On Delete";

            if (Notebook.Id > 0)
            {
                await _service.Delete(Notebook.Id);
            }

            return LocalRedirect("/notebooks");
        }
    }
}

src/Api/Areas/Notebooks/Pages/Form.cshtml.cs
using CloudDrive.Services.Notebooks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CloudDrive.Api.Areas.Notebooks.Pages
{
    public class FormPage : PageModel
    {
        private readonly INotebooksService _service;

        [BindProperty]
        public NotebookDto Notebook { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        public FormPage(INotebooksService service)
        {
            _service = service;
        }

        public void OnGetCreate()
        {
            ViewData["PageTitle"] = "On Create";
        }

        public async Task OnGetUpdateAsync()
        {
            ViewData["PageTitle"] = "On Update";

            if (Id > 0)
            {
                var result = await _service.Get(Id);

                if (result.IsSuccssfull)
                {
                    Notebook = result.Data;
                }
            }
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (Id > 0)
            {
                await _service.Update(Id, Notebook);
            }
            else
            {
                await _service.Insert(Notebook);
            }

            return LocalRedirect("/notebooks");
        }

    
    }
}

src/Api/Areas/Notebooks/Pages/Index.cshtml.cs
using CloudDrive.Services.Notebooks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CloudDrive.Api.Areas.Notebooks.Pages
{
	[Authorize]
	public class IndexPage : PageModel
	{
		private readonly INotebooksService _service;

		[BindProperty]
		public List<NotebookDto> Notebooks { get; set; }

		[BindProperty(SupportsGet = true)]
		public int Id { get; set; }

		public IndexPage(INotebooksService service)
		{
			_service = service;
		}

		public async Task OnGet()
		{
			ViewData["PageTitle"] = "Index page";

			Notebooks = await _service.Get();
		}
	}
}

src/Api/Areas/UserCreditCards/Pages/Delete.cshtml.cs
using CloudDrive.Services.CreditCards;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.CreditCards;

namespace clouddrive.Areas.UserCreditCards.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly ICreditCardsServices _service;
        [BindProperty]
        public CloudDrive.Domain.Result<CreditCardsDto> credirCard { get; set; }
        [BindProperty]
        public int CardId { get; set; }

        public DeleteModel(ICreditCardsServices service)
        {
            _service = service;
        }

        public async Task OnGet(int Id)
        {
            var result = await _service.GetAsync(Id);
            CardId = Id;
            credirCard = result;

        }
        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            else
            {
                var result = await _service.DeleteAsync(credirCard.Data.Id);
                credirCard.IsSuccssfull = result.IsSuccssfull;
                credirCard.Message = result.Message;
                return LocalRedirect("/Index");
            }
        }
    }
}

src/Api/Areas/UserPasswords/Pages/Delete.cshtml.cs
using CloudDrive.Services.UserPasswords;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CloudDrive.Api.Areas.UserPasswords.Pages
{
	public class DeletePage : PageModel
	{
		private readonly IUserPasswordsService _service;

		[BindProperty]
		public UserPasswordDto UserPassword { get; set; }

		[BindProperty(SupportsGet = true)]
		public int Id { get; set; }

		public DeletePage(
			IUserPasswordsService service
		)
		{
			_service = service;
		}

		public async Task OnGet()
		{
			ViewData["PageTitle"] = "On Delete";

			if (Id > 0)
			{
				var result = await _service.GetAsync(Id);

				if (result.IsSuccssfull)
				{
					UserPassword = result.Data;
				}
			}
		}

		public async Task<IActionResult> OnPost()
		{
			await _service.DeleteAsync(UserPassword.Id);

			return LocalRedirect("/user-passwords");
		}
	}
}

src/Api/Controllers/Api/NotebooksController.cs
using CloudDrive.Services.Notebooks;
using Microsoft.AspNetCore.Mvc;

namespace CloudDrive.Api.Controllers.Api
{
	[Route("/api/Notebooks")]

	public class NotebooksController : ControllerBase
	{
		private readonly INotebooksService _service;

		public NotebooksController(INotebooksService service)
		{
			_service = service;
		}

		[HttpGet]
		public async Task<IActionResult> Get()
		{
			return Ok(await _service.Get());
		}

		[HttpPost]
		public async Task<IActionResult> Post([FromBody] NotebookDto notebook)
		{
			var result = await _service.Insert(notebook);

			if (result.IsSuccssfull)
			{
				return Ok(result.Data);
			}

			return BadRequest(result);
		}


		[HttpGet("{id}")]
		public async Task<IActionResult> Get(int id)
		{
			var result = await _service.Get(id);

			if (result.IsSuccssfull)
			{
				return Ok(result.Data);
			}

			return NotFound(result);
		}

		[HttpDelete("{id}")]
		public async Task<IActionResult> Delete([FromRoute] int id)
		{
			var result = await _service.Delete(id);

			if (result.IsSuccssfull)
			{
				return NoContent();
			}
			else
			{
				return BadRequest(result);
			}
		}

		[HttpPut("{id}")]
		public async Task<IActionResult> Update([FromRoute] int id, [FromBody] NotebookDto user)
		{
			var result = await _service.Update(id, user);

			if (result.IsSuccssfull)
			{
				return Ok(result.Data);
			}
			else
			{
				return BadRequest(result);
			}
		}
	}

}

src/Api/Areas/Notebooks/Pages/Delete.cshtml
@page "{id}"

@using Microsoft.AspNetCore.Mvc.Localization

@model CloudDrive.Api.Areas.Notebooks.Pages.DeletePage

@inject IHtmlLocalizer<CloudDrive.SharedResource> Localizer

@{
	Layout = "/Views/Shared/_Layout.cshtml";
}

<div class="flex flex-col space-y-10 mt-10">
	<p class="text-red-500 font-bold text-xl mb-4 w-full">
		Are you sure you want to delete the nootebook <span>@Model.Notebook.Name</span>?
	</p>

	<form asp-area="Notebooks" asp-page="/Delete" asp-route-id="Id" method="post">
		<input asp-for="Notebook.Id" type="hidden" />

		<div class="mb-5 ">
			<label
				class="text-primary-500 font-bold md:text-right mb-1 md:mb-0 pr-4 dark:text-primary-400 w-20 inline-block"
				asp-for="Notebook.Name">
			</label>

			<input
				class="bg-gray-200 dark:bg-slate-800 appearance-none border-2 dark:border-slate-700 rounded py-2 px-4 dark:text-slate-500 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-primary-500"
				asp-for="Notebook.Name" type="text" placeholder="Name" disabled />

			<span asp-validation-for="Notebook.Name" class="text-danger">
			</span>
		</div>

		<div class="mb-5">
			<label
				class=" text-primary-500 font-bold md:text-right mb-1 md:mb-0 pr-4 dark:text-primary-400 w-20 inline-block"
				asp-for="Notebook.Category">
			</label>

			<input
				class="bg-gray-200 dark:bg-slate-800 appearance-none border-2 dark:border-slate-700 rounded py-2 px-4 dark:text-slate-500 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-primary-500"
				asp-for="Notebook.Category" type="text" placeholder="Category" disabled />

			<span asp-validation-for="Notebook.Category" class="text-danger">
			</span>
		</div>

		<div class="mb-5">
			<label
				class=" text-primary-500 font-bold md:text-right mb-1 md:mb-0 pr-4 dark:text-primary-400 w-20 inline-block"
				asp-for="Notebook.Color">
			</label>

			<input
				class="bg-gray-200 dark:bg-slate-800 appearance-none border-2 dark:border-slate-700 rounded py-2 px-4 dark:text-slate-500 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-primary-500"
				asp-for="Notebook.Color" type="text" placeholder="Color" disabled />

			<span asp-validation-for="Notebook.Color" class="text-danger">
			</span>
		</div>

		<button type="submit" class="btn-primary w-fit px-5 py-2 mt-4">
			Delete
		</button>

		<a asp-area="Notebooks" asp-page="/Index" class="w-fit px-5 py-2 mt-4">
			@Localizer["Cancel"]
		</a>
	</form>
</div>

src/Api/Areas/Notebooks/Pages/Form.cshtml
@page "/notebooks/{handler}/{id?}"

@model CloudDrive.Api.Areas.Notebooks.Pages.FormPage

@{
	Layout = "/Views/Shared/_Layout.cshtml";
}

<form asp-area="Notebooks" class="ml-10 mt-5 w-full max-w-sm" asp-page="/Form" asp-route-id="Id" method="post">
	<div class="mb-5">
		<label class="dark:text-primary-400 text-primary-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
			asp-for="Notebook.Name"></label>
		<input asp-for="Notebook.Name"
			class="bg-gray-200 appearance-none border-2 border-gray-200 rounded py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-primary-500"
			type="text" placeholder="Name" />
		<span asp-validation-for="Notebook.Name" class="text-danger"></span>
	</div>

	<div class="mb-5">
		<label class="dark:text-primary-400 text-primary-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
			asp-for="Notebook.Category"></label>
		<input
			class="bg-gray-200 appearance-none border-2 border-gray-200 rounded py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-primary-500"
			asp-for="Notebook.Category" type="text" placeholder="Category" />
		<span asp-validation-for="Notebook.Category" class="text-danger"></span>
	</div>

	<div class="mb-5">
		<label class="dark:text-primary-400 text-primary-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
			asp-for="Notebook.Color"></label>
		<input
			class=" bg-gray-200 appearance-none border-2 border-gray-200 rounded py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-primary-500"
			asp-for="Notebook.Color" type="color" placeholder="Color" />
		<span asp-validation-for="Notebook.Color" class="text-danger"></span>
	</div>

	<button type="submit" class="btn-primary w-fit px-5 py-2">
		Save
	</button>
</form>

src/Api/Areas/Notebooks/Pages/Index.cshtml
@page

@model CloudDrive.Api.Areas.Notebooks.Pages.IndexPage

@{
	Layout = "/Views/Shared/_Layout.cshtml";
}
<div class="my-10 mx-10 flex flex-col space-y-2">
	<a asp-area="Notebooks" asp-page="/Form" class="btn-primary w-fit px-5 py-2" asp-page-handler="create">
		Add note
	</a>

	<ol class="flex space-y-2 flex-col">
		@foreach (var item in Model.Notebooks)
		{
			<li>
				<notebook-item name="@item.Name" item-id="@item.Id"></notebook-item>
			</li>

		}
	</ol>
</div>

@section Scripts {
	<script src="/components/notebook-item.js"></script>
}